### ISSUE TITLE
copy for web site

### ISSUE THREAD

**Issue by markdav-is** [DarkMatterOregon/dark-matter-static-web#18]
Dark Matter Consulting will partner with your team to get your Enterprise Data Warehouse up, operational and providing valuable insight into your business operations quickly and accurately with a new ERP implementation like Microsoft Dynamics 365 or any other ERP system. Dark Matter Consulting and Brooklyn Brewery have teamed up to develop and launch an enterprise reporting system that provides mission critical tax and regulatory reporting not available out of the box in D365 as well as filling other reporting gaps. The system allows Brooklyn Brewery to operate within the boundaries of state and federal brewer’s operational regulations and has also been instrumental in exposing process and data quality issues in the transaction system. The cloud-based system architecture consists of several lean and very efficient data processing technologies in addition to industry leading best practices using Kimball data warehousing design principles. The operational costs and initial capital expenditures of a cloud-based system are significantly lower then an onsite EDW implementation.
- Azure SQL Data Warehouse the fast, flexible and trusted cloud based data warehouse that lets you scale, compute in a secure environment, with a massively parallel processing architecture.
- D365 BYOD lets you export one or more data entities that are available in D365 Finance and Operations with more than 1,700 data entities are available out of the box to eliminate the need for costly replication systems to get data out of the transaction system into a warehouse staging environment or operational data store.
- Azure Data Factory is a hybrid data integration service that allows you to create, schedule and orchestrate your E1TL/ELT SSIS workflows giving you the ability to orchestrate SSIS packages to load data into dimensional models and data marts in the data warehouse
- SSRS provides the platform to fulfill specific reporting needs and subscription-based reporting delivery from the Enterprise Data Warehouse.

These technologies combined with the Data Warehouse and Business Intelligence experience Dark Matter Consulting brings to the table have contributed to the successful completion of the Brooklyn Brewery BI/DW implementation allowing the team to meet reporting requirements and complete the project on time and under budget.

**Comment by danbillow** [comment]
This is just a stake in the sand, if there's edits that we should make let's do it..

**Comment by mckelveygreg** [comment]
Added to craft Brew page
