### ISSUE TITLE
Art asset requests:

### ISSUE THREAD

**Issue by mckelveygreg** [DarkMatterOregon/dark-matter-static-web#2]
- [x] Landing page image (are we sticking with Space?)
- [x] Official fonts
- [ ] Color pallet
- [x] Logo
- [x] Header Logo ?
- [x] Font Awesome Icons

**Comment by markdav-is** [comment]
I'm a fan of the reversed space images. 
<img width="800" alt="screen shot 2019-01-12 at 9 05 30 am" src="https://user-images.githubusercontent.com/311063/51076120-4c4c4000-1649-11e9-9c11-a9b03f414d71.png">

**Comment by markdav-is** [comment]
so i guess part of the question is if you want to composit the images in html or have a single image that already composed.

**Comment by mckelveygreg** [comment]
I feel that it will be more responsive to composit it in html? Unless there is a really specific way you want it.. 
Also, the reverse space looks awesome!

**Comment by jessicabob** [comment]
Body Font? 

<style>
@import url('https://fonts.googleapis.com/css?family=Raleway');
</style> 

font-family: 'Raleway', sans-serif;

**Comment by mckelveygreg** [comment]
Do you have the NASA black and white hex codes?

**Comment by jessicabob** [comment]
White = #fbfcfb
Black = #070a0e
